# Sample data for the Apply Abroad Lab Application Tracker Pro
# 20 real PhD/postdoc positions taken from applyabroadlab.com on 27 September 2026.
# Outreach dates, statuses and replies are illustrative so the dashboard has something to show.

# (id, title, institution, country, city, level, research_area, funding, deadline, url, supervisor, supervisor_email)
POSITIONS = [
    (3434, "Post Doc: Learning Interactions in Collective Cell Migration", "Vrije Universiteit Amsterdam", "Netherlands", "Amsterdam", "Postdoc", "Physics", "Fully Funded", "2026-09-30",
     "https://www.academictransfer.com/en/jobs/362788/post-doc-learning-interactions-in-collective-cell-migration/", "", ""),
    (6417, "MSCA-DN PhD in Pharmacological Therapy for Leukodystrophies", "Amsterdam UMC", "Netherlands", "Amsterdam", "PhD", "Medical Sciences; Neurosciences", "Fully Funded", "2026-10-05",
     "https://www.academictransfer.com/en/jobs/363691/msca-dn-phd-in-pharmacological-therapy-for-leukodystrophies-rome-it/", "", ""),
    (7806, "PhD Positions in Human-Centred Artificial Intelligence", "Aalborg University", "Denmark", "Aalborg", "PhD", "Human-Centred AI", "Fully Funded", "2026-11-13",
     "https://aau.varbi.com/en/what:job/jobID:972965/", "", ""),
    (6357, "PhD Candidate: Multi-Methods Project on Negation Across Languages", "University of Amsterdam", "Netherlands", "Amsterdam", "PhD", "Language Sciences; Psychology", "Fully Funded", "2026-10-12",
     "https://www.academictransfer.com/en/jobs/363542/phd-candidate-within-a-multi-methods-project-on-negation-across-languages/", "", ""),
    (6470, "PhD Position: Beyond the Odds - Pathways to Gambling-Related Harm", "Radboud University", "Netherlands", "Nijmegen", "PhD", "Economics; Psychology", "Fully Funded", "2026-09-30",
     "https://www.academictransfer.com/en/jobs/363826/phd-position-beyond-the-odds-unravelling-pathways-to-gambling-related-harm/", "", ""),
    (1044, "PhD Position in Time-Reflection of Subwavelength THz Waves", "ETH Zurich", "Switzerland", "Zurich", "PhD", "Physics - Applied Physics", "Not Stated", "",
     "https://www.jobs.ethz.ch/job/en/JOPG_ethz_VLtNEC6HFLUrmk6007?mw_source=academicpositions", "", ""),
    (5638, "Postdoc in Machine Learning and Surrogate Modelling", "University of Luxembourg", "Luxembourg", "Esch-sur-Alzette", "Postdoc", "Computer Science - AI", "Fully Funded", "",
     "https://www.uni.lu/en/jobs/postdoc-in-machine-learning-and-surrogate-modelling/", "", ""),
    (6373, "PhD: Microfluidics to Observe and Manipulate Coacervate Droplets", "University of Groningen", "Netherlands", "Groningen", "PhD", "Engineering; Biological Sciences", "Fully Funded", "2026-10-11",
     "https://www.academictransfer.com/en/jobs/363590/phd-position-using-microfluidics-to-observe-and-manipulate-coacervate-droplets/", "", ""),
    (6116, "Two Postdoctoral Positions in Mitochondrial Cell Biology", "Institut Imagine", "France", "Paris", "Postdoc", "Biology", "Fully Funded", "2026-10-02",
     "https://www.welcometothejungle.com/fr/companies/institut-imagine/jobs/two-2-postdoctoral-positions-in-mitochondrial-cell-biology_paris", "", ""),
    (2547, "Doctoral Student in Environmental Law Specialising in Nuclear Power", "Uppsala University", "Sweden", "Uppsala", "PhD", "Environmental Law", "Fully Funded", "2026-10-01",
     "https://uu.varbi.com/en/what:job/jobID:953285/", "", ""),
    (7363, "PhD in Integrated Circuit Group on Transceivers for Optical Communications", "Eindhoven University of Technology", "Netherlands", "Eindhoven", "PhD", "Engineering", "Fully Funded", "2026-10-18",
     "https://www.academictransfer.com/en/jobs/364085/phd-in-the-integrated-circuit-group-on-transceivers-for-optical-communications/", "", ""),
    (7619, "Postdoc in Structural Analysis of Carbon Materials for Energy Storage", "Uppsala University", "Sweden", "Uppsala", "Postdoc", "Carbon Materials; Electrochemistry", "Not Stated", "2026-10-26",
     "https://uu.varbi.com/en/what:job/jobID:972884/", "", ""),
    (5708, "Postdoc: Multiphysics Modelling of Laser-Regolith Interaction (Moon)", "Technical University of Denmark", "Denmark", "Kongens Lyngby", "Postdoc", "Mechanical Engineering; Space", "Not Stated", "2026-10-06",
     "https://efzu.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/job/8059/", "", ""),
    (5649, "Postdoctoral Researcher in Quantum Communications", "University of Luxembourg", "Luxembourg", "Esch-sur-Alzette", "Postdoc", "Physics - Quantum Optics", "Fully Funded", "",
     "https://www.uni.lu/en/jobs/postdoctoral-researcher-in-quantum-communications/", "", ""),
    (7501, "Research Associate in Steel Structures and Sustainable Design", "University of Sheffield", "United Kingdom", "Sheffield", "Postdoc", "Civil Engineering", "Fully Funded", "2026-10-22",
     "https://university-of-sheffield.contactrh.com/jobs/11046/44464617", "", ""),
    (4479, "Postdoc in Synthesis and Crystal Growth of Molecular Conductors", "Chalmers University of Technology", "Sweden", "Gothenburg", "Postdoc", "Chemistry; Materials Chemistry", "Fully Funded", "2026-10-15",
     "https://www.chalmers.se/en/about-chalmers/work-with-us/vacancies/?rmpage=job&rmjob=15046&rmlang=UK", "Daniel Weber", "daniel.weber@chalmers.se"),
    (5800, "PhD Candidate in Children's Media in English (CLEAR Group)", "NTNU", "Norway", "Trondheim", "PhD", "Children's Media Studies", "Not Stated", "2026-09-30",
     "https://www.jobbnorge.no/en/available-jobs/job/306713/phd-candidate-in-childrens-media-in-english", "", ""),
    (6100, "PhD: Chemical Activity of Air Pollutants via Laser Spectroscopy", "Forschungszentrum Jülich", "Germany", "Jülich", "PhD", "Environmental Chemistry", "Not Stated", "",
     "https://recruiting.fz-juelich.de/jobposting/feb0efc501ddc3d5ab9b2c01d600e59045c7cff90", "", ""),
    (5770, "Doctoral Fellow: Lunar Resource Production (LuMoCX / ERC)", "Ghent University", "Belgium", "Ghent", "PhD", "Space Resources", "Not Stated", "2026-12-07",
     "https://www.ugent.be/en/work/scientific/doctoral-fellow-137", "", ""),
    (5676, "Postdoctoral Fellows in Proteomics: Neurodevelopment and Cancer", "University of Helsinki", "Finland", "Helsinki", "Postdoc", "Proteomics; Biomedical Science", "Not Stated", "2026-09-30",
     "https://jobs.helsinki.fi/job/Helsinki-Postdoctoral-Research-Fellows-in-Proteomics/1370111857/", "", ""),
]

# (first_email, template, cv_version, proposal_version, follow_up_1, follow_up_2, follow_up_3, status)
TRACKING = [
    ("2026-08-05", "Template A", "CV_v4", "Prop_v2", "2026-08-19", "2026-09-02", "", "Positive Reply"),
    ("2026-08-10", "Template A", "CV_v4", "Prop_v2", "2026-08-24", "", "", "No Reply"),
    ("2026-09-15", "Template B", "CV_v5", "Prop_v3", "", "", "", "Sent"),
    ("2026-08-12", "Template B", "CV_v4", "", "2026-08-26", "", "", "Neutral Reply"),
    ("2026-07-28", "Template A", "CV_v3", "Prop_v1", "2026-08-11", "2026-08-25", "2026-09-08", "Rejected"),
    ("2026-09-01", "Template B", "CV_v5", "Prop_v3", "2026-09-15", "", "", "Interview Invitation"),
    ("2026-09-18", "Custom", "CV_v5", "Prop_v3", "", "", "", "Sent"),
    ("2026-08-20", "Template A", "CV_v4", "Prop_v2", "2026-09-03", "", "", "No Reply"),
    ("2026-08-25", "Template B", "CV_v4", "", "2026-09-08", "", "", "Positive Reply"),
    ("2026-07-20", "Template A", "CV_v3", "Prop_v1", "2026-08-03", "2026-08-17", "", "Accepted"),
    ("2026-09-20", "Template B", "CV_v5", "Prop_v3", "", "", "", "Sent"),
    ("2026-09-05", "Custom", "CV_v5", "", "2026-09-19", "", "", "No Reply"),
    ("2026-08-30", "Template B", "CV_v4", "Prop_v2", "2026-09-13", "", "", "Neutral Reply"),
    ("2026-09-22", "Template A", "CV_v5", "Prop_v3", "", "", "", "Sent"),
    ("2026-08-15", "Template C", "CV_v4", "", "2026-08-29", "2026-09-12", "", "No Reply"),
    ("2026-09-10", "Custom", "CV_v5", "Prop_v3", "", "", "", "Interview Invitation"),
    ("2026-08-08", "Template A", "CV_v4", "Prop_v2", "2026-08-22", "", "", "Rejected"),
    ("2026-09-24", "Template B", "CV_v5", "", "", "", "", "Sent"),
    ("2026-09-12", "Template A", "CV_v5", "Prop_v3", "", "", "", "No Reply"),
    ("2026-08-18", "Template C", "CV_v4", "Prop_v2", "2026-09-01", "", "", "Neutral Reply"),
]

# (row_index_into_POSITIONS, reply_date, reply_status, summary, meeting_date, outcome, next_action)
RESPONSES = [
    (0, "2026-09-08", "Positive Reply", "Expressed interest; asked for the full proposal and a funding plan", "2026-09-22", "Proposal Requested", "Send the two-page research proposal"),
    (3, "2026-09-02", "Neutral Reply", "No budget at the moment but open to a conversation", "", "Info Received", "Check NWO grant options"),
    (4, "2026-09-14", "Rejected", "Position has been filled", "", "Closed", "Remove from follow-up list"),
    (5, "2026-09-20", "Interview Invitation", "Invited to a 30-minute online interview with the group leader", "2026-10-03", "Interview Scheduled", "Prepare a 5-minute research pitch"),
    (8, "2026-09-16", "Positive Reply", "Asked for a writing sample and two referees", "", "Proposal Requested", "Send writing sample and referee list"),
    (9, "2026-08-30", "Accepted", "Formal acceptance; start date January 2027", "2026-09-05", "Accepted", "Start the residence-permit process"),
    (12, "2026-09-19", "Neutral Reply", "Position still open but priority is given to internal candidates", "", "Info Received", "Follow up again in November"),
    (15, "2026-09-21", "Interview Invitation", "Invited to an introductory meeting with the research team", "2026-10-08", "Interview Scheduled", "Review the group's recent papers"),
    (16, "2026-09-05", "Rejected", "Research area does not match", "", "Closed", "Remove from follow-up list"),
    (19, "2026-09-15", "Neutral Reply", "Referred to another colleague in the same faculty", "", "Info Received", "Contact the referred professor"),
]
